/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Admin (void);
GtkWidget* create_Authentification (void);
GtkWidget* create_Gestion_bureau_de_vote (void);
GtkWidget* create_Gestion_des_r__clamations (void);
GtkWidget* create_Gestion_des_observateurs (void);
GtkWidget* create_Gestion_des_listes___lectorales (void);
GtkWidget* create_Gestion_des_utilisateurs (void);
GtkWidget* create_Platforme_de_vote (void);
GtkWidget* create_Pr__inscription (void);
GtkWidget* create_window8 (void);
